[tool.black]
line-length = 79
exclude = '''
(
  /(
    reference # original files from DataDog
    exporter/opentelemetry-exporter-prometheus-remote-write/src/opentelemetry/exporter/prometheus_remote_write/gen
  )/
)
'''
