name: Contrib Repo Tests

on:
  push:
    branches-ignore:
    - 'release/*'
  pull_request:
env:
  CORE_REPO_SHA: 3b813eb9921e709538dd1b07fa7a5f93600fbec1

jobs:
  build:
    env:
      # We use these variables to convert between tox and GHA version literals
      py35: 3.5
      py36: 3.6
      py37: 3.7
      py38: 3.8
      pypy3: pypy3
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        python-version: [ py35, py36, py37, py38, pypy3 ]
        package: ["instrumentation", "exporter", "sdkextension"]
        os: [ ubuntu-latest ]
        include:
          # py35-instrumentation segfaults on 18.04 so we instead run on 20.04
          - python-version: py35
            package: instrumentation
            os: ubuntu-20.04
        exclude:
          - os: ubuntu-latest
            python-version: py35
            package: instrumentation
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Checkout Core Repo @ SHA - ${{ env.CORE_REPO_SHA }}
        uses: actions/checkout@v2
        with:
          repository: open-telemetry/opentelemetry-python
          ref: ${{ env.CORE_REPO_SHA }}
          path: opentelemetry-python-core
      - name: Set up Python ${{ env[matrix.python-version] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env[matrix.python-version] }}
      - name: Install tox
        run: pip install -U tox-factor
      - name: Cache tox environment
        # Preserves .tox directory between runs for faster installs
        uses: actions/cache@v2
        with:
          path: .tox
          key: tox-cache-${{ matrix.python-version }}-${{ matrix.package }}-${{ matrix.os }}-${{ hashFiles('tox.ini', 'dev-requirements.txt') }}
      - name: run tox
        run: tox -f ${{ matrix.python-version }}-${{ matrix.package }}
  misc:
    strategy:
      fail-fast: false
      matrix:
        tox-environment: [ "docker-tests", "lint" ]
    name: ${{ matrix.tox-environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Checkout Core Repo @ SHA ${{ env.CORE_REPO_SHA }}
        uses: actions/checkout@v2
        with:
          repository: open-telemetry/opentelemetry-python
          ref: ${{ env.CORE_REPO_SHA }}
          path: opentelemetry-python-core
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tox
        run: pip install -U tox
      - name: Cache tox environment
        # Preserves .tox directory between runs for faster installs
        uses: actions/cache@v2
        with:
          path: .tox
          key: tox-cache-${{ matrix.tox-environment }}-${{ hashFiles('tox.ini', 'dev-requirements.txt') }}
      - name: run tox
        run: tox -e ${{ matrix.tox-environment }}
